# Github actions to build
# and push wheel files
name: Build Quarto Wheels

on:
  push:
    workflow_dispatch:

jobs:
  build_wheels:
    name: Wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: robinraju/release-downloader@v1.8
        if: contains(matrix.os, 'macos')
        with:
          repository: "quarto-dev/quarto-cli"
          latest: true
          fileName: "quarto-*-macos.tar.gz"

      - if: contains(matrix.os, 'macos')
        run: |
          mkdir quarto
          mv quarto-*-macos.tar.gz quarto
          pushd quarto
          tar -xvf quarto-*-macos.tar.gz
          rm quarto-*-macos.tar.gz
          cd bin
          touch __init.py__
          cd ..
          cd share
          touch __init.py__
          cd ..
          popd quarto

      - uses: robinraju/release-downloader@v1.8
        if: contains(matrix.os, 'windows')
        with:
          repository: "quarto-dev/quarto-cli"
          latest: true
          fileName: "quarto-*-win.zip"

      - if: contains(matrix.os, 'windows')
        run: |
          unzip -xvf quarto-*-win.zip
          rm quarto-*-win.zip

      - uses: robinraju/release-downloader@v1.8
        if: contains(matrix.os, 'ubuntu')
        with:
          repository: "quarto-dev/quarto-cli"
          latest: true
          fileName: "quarto-*-linux-arm64.tar.gz"

      - if: contains(matrix.os, 'ubuntu')
        run: |
          tar -xvf quarto-*-linux-arm64.tar.gz
          rm quarto-*-linux-arm64.tar.gz

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: py3*-macosx_universal2
          CIBW_PLATFORM: macos
          CIBW_ARCHS: universal2

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl