# Github actions to build
# and push wheel files
name: Build Quarto Wheels

on:
  push:
    workflow_dispatch:

jobs:
  build_wheels:
    name: Wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - uses: robinraju/release-downloader@v1.8
        if: contains(matrix.os, 'macos')
        with:
          repository: "quarto-dev/quarto-cli"
        latest: true
        fileName: "quarto-1.4.542-macos.tar.gz"

      - if: contains(matrix.os, 'macos')
        run: |
          tar -xvf quarto-1.4.542-macos.tar.gz
          rm quarto-1.4.542-macos.tar.gz

      - uses: robinraju/release-downloader@v1.8
        if: contains(matrix.os, 'windows')
        with:
          repository: "quarto-dev/quarto-cli"
        latest: true
        fileName: "quarto-1.4.542-win.zip"

      - if: contains(matrix.os, 'ubuntu')
        run: |
          unzip -xvf quarto-1.4.542-win.zip
          rm quarto-1.4.542-win.zip

      - uses: robinraju/release-downloader@v1.8
        if: contains(matrix.os, 'ubuntu')
        with:
          repository: "quarto-dev/quarto-cli"
        latest: true
        fileName: "quarto-1.4.542-linux-arm64.tar.gz"

      - if: contains(matrix.os, 'ubuntu')
        run: |
          tar -xvf quarto-1.4.542-linux-arm64.tar.gz
          rm quarto-1.4.542-linux-arm64.tar.gz

      - uses: pypa/cibuildwheel@v2.16

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl